services:
  swarms-agent-server:
    image: 0xii/swarms-template:0.0.1
    volumes:
      - swarms:/app
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - MODEL_NAME=${MODEL_NAME}
    command: python3 main.py && sleep infinity

volumes:
  swarms:
